# Generated by Django 5.2.8 on 2025-11-25 23:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cientifico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: Dr. Malito', max_length=100)),
                ('especialidad', models.CharField(default='Rayos Láser', max_length=100)),
                ('biografia', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Componente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Invento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: Inyector de Pánico', max_length=150)),
                ('descripcion', models.TextField()),
                ('probabilidad_exito', models.IntegerField(help_text='% de que funcione sin explotar')),
            ],
        ),
        migrations.CreateModel(
            name='MaterialSospechoso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('nivel_peligro', models.CharField(choices=[('BAJO', 'Causa picazón leve'), ('MEDIO', 'Inflamable o explosivo'), ('ALTO', 'Peligro biológico/radiactivo'), ('EXTREMO', 'Provoca el fin del mundo')], default='BAJO', max_length=10)),
                ('es_ilegal', models.BooleanField(default=True, help_text='¿La policía busca esto?')),
                ('stock_gramos', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Esbirro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='Igor', max_length=100)),
                ('tiene_joroba', models.BooleanField(default=True)),
                ('nivel_lealtad', models.IntegerField(default=1, help_text='Del 1 al 10 (1 = Traicionero, 10 = Se lanza al volcán)')),
                ('cientifico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='esbirros', to='laboratorio.cientifico')),
            ],
        ),
        migrations.CreateModel(
            name='ProtocoloAutodestruccion',
            fields=[
                ('invento', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='laboratorio.invento')),
                ('codigo_activacion', models.CharField(default='1234', max_length=20)),
                ('segundos_cuenta_regresiva', models.IntegerField(default=10)),
                ('mensaje_despedida', models.CharField(default='¡Hasta la vista, baby!', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Receta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=1, help_text='Unidades necesarias')),
                ('componente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laboratorio.componente')),
                ('invento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laboratorio.invento')),
            ],
        ),
        migrations.AddField(
            model_name='invento',
            name='componentes',
            field=models.ManyToManyField(through='laboratorio.Receta', to='laboratorio.componente'),
        ),
    ]
