# Generated by Django 5.2.8 on 2025-11-26 00:25

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='esbirro',
            name='tiene_joroba',
        ),
        migrations.RemoveField(
            model_name='protocoloautodestruccion',
            name='segundos_cuenta_regresiva',
        ),
        migrations.AddField(
            model_name='invento',
            name='fecha_fabricacion',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='cientifico',
            name='especialidad',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='cientifico',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='esbirro',
            name='nivel_lealtad',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='esbirro',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='invento',
            name='nombre',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='invento',
            name='probabilidad_exito',
            field=models.IntegerField(help_text='Porcentaje de 0 a 100', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='materialsospechoso',
            name='es_ilegal',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='materialsospechoso',
            name='nivel_peligro',
            field=models.CharField(default='BAJO', max_length=20),
        ),
        migrations.AlterField(
            model_name='protocoloautodestruccion',
            name='codigo_activacion',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='protocoloautodestruccion',
            name='mensaje_despedida',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='receta',
            name='cantidad',
            field=models.IntegerField(default=1),
        ),
    ]
