# Generated by Django 5.2.8 on 2025-11-26 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorio', '0002_remove_esbirro_tiene_joroba_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='esbirro',
            name='tiene_joroba',
            field=models.BooleanField(default=True),
        ),
    ]
