# Generated by Django 5.2.8 on 2025-11-26 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorio', '0003_esbirro_tiene_joroba'),
    ]

    operations = [
        migrations.AddField(
            model_name='cientifico',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='cientificos/'),
        ),
        migrations.AddField(
            model_name='invento',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='inventos/'),
        ),
    ]
