# Generated by Django 5.2.8 on 2025-11-26 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorio', '0004_cientifico_foto_invento_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialsospechoso',
            name='nivel_peligro',
            field=models.CharField(choices=[('BAJO', 'Bajo - Causa picazón'), ('MEDIO', 'Medio - Inflamable'), ('ALTO', 'Alto - Radioactivo'), ('EXTREMO', 'Extremo - Fin del mundo')], default='BAJO', max_length=20),
        ),
    ]
