# Generated by Django 5.2.8 on 2025-11-28 17:39

import laboratorio.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorio', '0005_alter_materialsospechoso_nivel_peligro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cientifico',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to=laboratorio.models.generar_nombre_unico),
        ),
        migrations.AlterField(
            model_name='invento',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to=laboratorio.models.generar_nombre_unico),
        ),
        migrations.AlterUniqueTogether(
            name='receta',
            unique_together={('invento', 'componente')},
        ),
    ]
