# Generated by Django 5.0 on 2025-11-29 18:00 # (La fecha y hora pueden variar)

from django.db import migrations
from django.core.management import call_command
import os

# Define la ruta a la carpeta 'fixtures' dentro de tu app
fixture_dir = os.path.abspath(os.path.join(os.path.dirname(__file__), '../fixtures'))
# El nombre de tu archivo JSON
fixture_filename = 'iqs_datos_final.json'

def load_fixture(apps, schema_editor):
    """Carga el fixture JSON."""
    fixture_file = os.path.join(fixture_dir, fixture_filename)
    # Llama al comando 'loaddata' de Django
    call_command('loaddata', fixture_file)

def unload_fixture(apps, schema_editor):
    """Función para revertir la carga (opcional)."""
    # En este caso, no hacemos nada al revertir, pero es buena práctica tenerla.
    print("Unloading fixture... (no action taken)")
    pass

class Migration(migrations.Migration):

    dependencies = [
        # ¡¡IMPORTANTE!! Revisa tu carpeta de migraciones y pon aquí el nombre
        # del archivo de migración ANTERIOR a este.
        # Probablemente sea '0006_auto_...' o el número que corresponda.
        ('laboratorio', '0006_alter_cientifico_foto_alter_invento_foto_and_more'), # <-- CAMBIA ESTO
    ]

    operations = [
        # Ejecuta la función 'load_fixture' cuando se aplica la migración
        migrations.RunPython(load_fixture, reverse_code=unload_fixture),
    ]